global:
  scrape_interval: 10s  # How often to scrape targets
  evaluation_interval: 10s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spark Master metrics
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']

  # Spark Worker metrics
  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8081']


